model:
  name: Qwen/Qwen2.5-3B-Instruct
  revision: aa8e72537993ba99e69dfaafa59ed015b17504d1

precision:
  condition_name: 4bit_nf4
  quantized: true
  load_in_4bit: true
  quantization_type: nf4
  compute_dtype: bfloat16
  use_double_quantization: false
